---
- hosts: nagios-server
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    mytext: |
      define host {
      use linux-server
      host_name host1
      alias Apache server host1
      address 172.31.47.240
      max_check_attempts 5
      check_period 24x7
      notification_interval 30
      notification_period 24x7
      }
      define host { 
      use linux-server
      host_name host2
      alias Apache server host2
      address 172.31.46.67
      max_check_attempts 5
      check_period 24x7
      notification_interval 30
      notification_period 24x7
      }
  tasks:
    - name: Add folder
      file:
        path: /usr/local/nagios/etc/servers/
        state: directory
        owner: nagios
        group: nagios
        mode: '0777'
    - name: add file
      file:
        path: /usr/local/nagios/etc/servers/host.cfg
        owner: nagios
        group: nagios
        state: touch
        mode: 777

    - name: Copy 
      copy:
        content: "{{ mytext }}"
        dest: '/usr/local/nagios/etc/servers/host.cfg'

    - name: Configure nagios conf file
      lineinfile: 
        dest: /usr/local/nagios/etc/nagios.cfg
        regexp: '#cfg_dir=/usr/local/nagios/etc/servers'
        line: 'cfg_dir=/usr/local/nagios/etc/servers'
        
    - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
      blockinfile:
        path: /usr/local/nagios/etc/objects/commands.cfg
        block: |
          define command{
          command_name check_nrpe
          command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
          } 
    - name: Restart service nagios
      service:
        name: nagios
        state: restarted

    
    