---
- hosts: nagios-server
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    mytext: |
      define host {
      use linux-server
      host_name host1
      alias Apache server host1
      address 52.86.53.73
      max_check_attempts 5
      check_period 24x7
      notification_interval 30
      notification_period 24x7
      }
  tasks:
    - name: Add folder
      file:
        path: /usr/local/nagios/etc/servers/
        state: directory
        mode: '0777'
    - name: add file
      file:
        path: /usr/local/nagios/etc/servers/host.cfg
        state: touch
        mode: 777

    - name: Copy 
      copy:
        content: "{{ mytext }}"
        dest: '/usr/local/nagios/etc/servers/host.cfg'
    - name: Restart service nagios
      service:
        name: nagios
        state: restarted
